### ISSUE TITLE
Wrong expectation on click card

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [antonybudianto/gitcard#1]
My expectation when clicking some card list is showing the detail about the card, like when we search `username`.

Current condition: redirect to GH Link

<img width="1418" alt="Screen Shot 2019-09-23 at 12 56 00" src="https://user-images.githubusercontent.com/51905113/65404187-bc7aaa80-de01-11e9-9a4d-916d6d1cfbf7.png">

**Comment by antonybudianto** [comment]
Now card can be clicked and searches the user
