### ISSUE TITLE
More mobile friendly

### ISSUE THREAD

**Issue by rizafahmi** [antonybudianto/gitcard#18]
Untuk layar dengan size kira-kira 350-an px, tampilannya sedikit 'rusak'.

<img width="452" alt="Screen Shot 2019-10-19 at 11 31 48" src="https://user-images.githubusercontent.com/1147918/67137733-1422ff00-f264-11e9-87b1-90e902dd7222.png">

**Comment by rizkyalviandra** [comment]
I'll take this
